name:                haskell-pet-project
version:             0.1.0.0
github:              "githubuser/haskell-pet-project"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-pet-project#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- servant-server
- servant-client
- resource-pool
- wai
- warp
- bytestring
- http-media
- servant
- http-media
- containers
- postgresql-simple
- http-client
- transformers >= 0.4
- monad-logger
- mtl
- HDBC
- time

library:
  source-dirs: src

executables:
  haskell-pet-project-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - haskell-pet-project

tests:
  haskell-pet-project-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - haskell-pet-project
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson < 2
